### ISSUE TITLE
Add a default, HTTPS-hosted dataset/collection

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#104]
## Use Case

GitHub pages is served via HTTPS, which means all loaded data must also be served via HTTPS. This means that the current default dataset (Mama Bear, Baby Bear, Goldilocks) can't be loaded. 

(I believe they can also only be loaded on the VPN currently too.)

## Acceptance Criteria

- Add a default collection to the `documentation` folder that can be loaded as static files from GitHub's file hosting.
- Collection should include one or more datasets that show off basic use cases for Timelapse Colorizer.

## Details
- Moving squares?
- Cool Voronoi visualization?

**Comment by toloudis** [comment]
Also, (possibly more importantly) if we are having a publicly accessible version of the app, we shouldn't have the default dataset be something that is unpublished work-in-progress internal data.

**Comment by ShrimpCryptid** [comment]
Closing this since going to the viewer directly is not part of our intended user flow. Users will be redirected to landing page.
