### ISSUE TITLE
Thresholding discovery, research, and design

### ISSUE THREAD

**Issue by lynwilhelm** [allen-cell-animated/nucmorph-colorizer#119]
### Description
- _Type of UX work needed (research, discovery and/or design_
- _Problem(s) to solve_

See implementation tickets:
https://github.com/allen-cell-animated/nucmorph-colorizer/issues/91
https://github.com/allen-cell-animated/nucmorph-colorizer/issues/90

***
_Below to be filled out by UX during kickoff Q&A to the best of current understanding_

### Size
_Effort level (xs, sm, m, lg, xl)_

### Scope
_What will we do? What will we NOT do?_

### User needs statement(s)
As a _[type of user]_, I need/want to _[action(s)]_, so that I can _[goal]_.

### Additional notes
_Knowns/unknowns, stakeholders, time/dependency considerations, deliverables_

**Comment by ShrimpCryptid** [comment]
![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/1e324c7a-0a54-489b-b1df-0b3188b6bfa5)

![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/5ea6b27a-2fe9-4466-bd0f-84373ca9b0c4)
Crude drawing, but the filters panel could live where the plot currently is, and the two of them could use tabs for switching between the views.
