### ISSUE TITLE
data: centroids and bounds of cells

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#13]
## Use Case

Add data that has the xy position of the centroid, and the bounding box of every cell.  

## Acceptance Criteria

A click on the viewport can console.log the xy coordinates of the cell's centroid.  Both bounding boxes and centroids in pixels.

## Details

Can we load json data that contains a 2d array or array-of-pairs like this?  Could also just store it as 1D array and then restructure it at load time. 
 Is it time to consider using a binary file format?  -- is there a generic well known file format for numeric array data that can be written from python and read in JS that isn't totally custom?  is it zarr?

**Comment by toloudis** [comment]
enables #7

**Comment by ShrimpCryptid** [comment]
Add logging for duration of time (log file written to same data output directory). Hook up with Python logging?
