### ISSUE TITLE
error exporting video

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#146]
## Description

See error message at bottom of the export dialog:

![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/2193409/2c8cc1b7-22d8-46bf-a49c-375cde1377bf)

## Expected Behavior

Expected video to be created without error

## Reproduction

Dataset is https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2FEMT_H2B%2Fcollection.json&dataset=3500005828_25&feature=Radial%20distance%20from%20colony%20centroid&color=matplotlib-cool

Not sure if this is reproducible but would be good to know what might cause it.

**Comment by ShrimpCryptid** [comment]
Did stopping and restarting the recording fix this instance of the error message, or did it stay bugged? It looks like the Canvas was in some sort of bugged state, but I can't dig deeper until I can reproduce this :((

**Comment by toloudis** [comment]
This was reported by Derek so we will need to check in with him if he has time/availability.
