### ISSUE TITLE
Update color palette selection

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#161]
## Description

Discussion from #152, raised by @toloudis:
> I have a slight concern that we haven't chosen the best palettes. This could be addressed in a future PR. I tend to trust the adobe and matplotlib more than iwanthue. My suggestion is that we pick a selection of palettes from a source like https://kwstat.github.io/pals/reference/discrete.html which has research paper references for most of the selections. It would be nice to be able to cite that the palettes have a basis in color theory and visualization science.

## Solution Steps
- Remove the iwanthue palettes once random colors are available? See #159 
- Implement the `kelly` color palette from https://kwstat.github.io/pals/reference/discrete.html

**Comment by toloudis** [comment]
* specific to categorical features
