### ISSUE TITLE
filter out feature values

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#17]
## Use Case

I would like to eliminate certain feature values from the view

## Acceptance Criteria

select a max and min value for a feature - could be interesting to do this as a two ended slider tht you can push in from either end.  
I am assuming we would just hide cells that are outside the selected range.  Requested by @niveditasa 

## Details

depends on #2
Where to put the controls?   I imagine a slider just below the color gradient and lined up with it.  Do we want to truncate the gradient or rescale the gradient to fit to the new min and max?  If the latter, then lining it up with the slider would be misleading.

**Comment by toloudis** [comment]
* make min and max be input controls
* add a new checkbox for "clamp min/max" vs "hide out of range values"

**Comment by ShrimpCryptid** [comment]
- Add a button to reset to default min/max once edited
