### ISSUE TITLE
Use feature keys instead of names

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#181]
## Use Case

- Enforce feature keys on datasets, where feature keys can only be lowercase alphanumeric characters or underscores.
  - Feature names will be human-readable strings with any allowed characters.
- Update all areas of the project that rely on feature names for storing/indexing features to use feature keys.
  - This allows the URL to do less string sanitization, resulting in hopefully a shorter URL.

**Comment by toloudis** [comment]
To be precise on wording in your first bullet, the `key` is the thing that should be lowercase alphanumeric + underscore.  Usually `key` and `id` are interchangeable.  Want to be careful on how we use `name`: is that a synonym for `key` or is it the displayable user-readable string?  If the latter, then it can have all kinds of characters.

**Comment by ShrimpCryptid** [comment]
The `name` will be the displayable user-readable string, yes!
