### ISSUE TITLE
Save settings to the URL

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#183]
Save backdrop key, brightness, saturation, and object opacity to the URL if changed from the defaults.

**Comment by toloudis** [comment]
Most important is to capture the settings, exact names are not so critical.

Suggestion:
bg-key=
bg-brightness=
bg-sat=
img-alpha= or fg-alpha=

outlier-mode=
outlier-color=
filtered-mode=
filtered-color=

show-path=
