### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#184]
## Use Case

- Should be easy for users to find the base repository to submit issues or feedback, and to find our documentation.
- ~~ALSO, add a link in the base GitHub README to the `colorizer-data` repo and our data format spec?~~

## Acceptance Criteria

- Add a "Report Issues" or "About" button somewhere on the UI?

**Comment by toloudis** [comment]
"Help" Menu with 2 items - 
1. Report an issue (links to gh issues page)
2. Documentation (links to main repo readme)

**Comment by ShrimpCryptid** [comment]
Documentation should link to a tutorial on how to use the web UI
