### ISSUE TITLE
Apply current threshold in scatterplot

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#185]
## Use Case

Extension of #94. 

## Acceptance Criteria
- Move threshold calculation code out of `ColorizeCanvas` so that it only needs to be calculated in one location on changes to threshold.
  - May also be a good opportunity to evaluate whether it's slow enough to move into a worker thread.
- Apply out-of-range coloration to the scatterplot.
  - Filter scatterplot data values by the current threshold, and move filtered points into their own trace.
  - Update whenever the threshold/thresholded values change.

## Details

- Threshold and scatterplot should stay in sync automatically. (Debouncing thresholds is OK)

**Comment by toloudis** [comment]
Bonus feature: toggle button in the plot tab, to apply filters or not apply filters.
