### ISSUE TITLE
blend dropped data that would otherwise flicker

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#21]
## Use Case

Outliers flicker on playback because they are given a unique color outside the active range.  This is visually distracting when playing back animation sequence.

## Acceptance Criteria

Checkbox:  "Blend dropped data if < __N__ Frames" where __N__ can be user choice (some small number like 1 or 2 hopefully).   Perhaps we could also give an option to have the cells disappear rather than get a special color.  

## Details

I think "blend" means to interpolate between two frames of data for cell on the same track.  This would be a totally new implementation in the main shader to try to figure out how to color a given pixel.

**Comment by toloudis** [comment]
revision:
When feature is loaded, fill in Nan/outlier/invalid values with interpolated values. Make sure outlier flag is true for all filled in values. Then can have checkbox control whether to check the outlier flag or simply use the feature value provided.

**Comment by ShrimpCryptid** [comment]
Seems like a non-issue currently. Users have lots of control over colors and likely don't want interpolation of their data without their knowledge.
