### ISSUE TITLE
Reevaluate Color Maps

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#217]
## Use Case
Viridis may be used in upcoming nucmorph figures.

## Acceptance Criteria

- Add viridis to the accepted maps: https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html
  - Optionally add additional maps from Viridis
![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/3e4abfe2-622e-4734-b459-ea35f21694fe)

## Details

- May also be a good opportunity to remove maps that are not particularly useful, or have false features.
- Also could add the other color maps that come with the standard Viridis package

**Comment by ShrimpCryptid** [comment]
How important is backwards compatibility for color maps? Should we still keep the old colors, but just not show them as options on the UI?

**Comment by ShrimpCryptid** [comment]
https://waldyrious.net/viridis-palette-generator/

**Comment by toloudis** [comment]
maybe we can re-evaluate and "finalize" all color maps as part of this ticket
