### ISSUE TITLE
Display collection names on the UI

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#220]
## Use Case

Add a display name for datasets or collections that can be shown on the UI.

## Acceptance Criteria

_Please describe how you know this is done_

## Details

- Does a collection's name for a dataset override its manifest name?

**Comment by toloudis** [comment]
Answer: yes, if someone went to the trouble of explicitly putting a "name":"My Display Name", I'd say that should have priority. For both a collection json and a dataset json.    One of the interesting tricks that we have to revisit is the idea of pre-fetching all the dataset jsons of a collection to read their name fields. A little messy. But maybe we can still populate the dropdown with info from the collection json.

**Comment by ShrimpCryptid** [comment]
Requires https://github.com/allen-cell-animated/colorizer-data/issues/35 to be completed first

**Comment by ShrimpCryptid** [comment]
See `collection_name` at the top of Lyndsay's design:

![Image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/097eb663-6d16-4344-b265-b3305d8231c6)
