### ISSUE TITLE
Update tooltip background color

### ISSUE THREAD

**Issue by lynwilhelm** [allen-cell-animated/nucmorph-colorizer#236]
## Description

Tooltip background color is darker than intended and look pretty stark against the white background.

## Expected Behavior

Hex #323233 was intended color, but while you're at it I think we can do even better! Perhaps add 86% opacity to that! Secondarily, I'm also open to a non-transparent color that's even lighter, and/or in line with the purple theme.

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by ShrimpCryptid** [comment]
Ended up implementing this as #323233 with a 90% transparency, because I found any more transparent than that made the tooltips somewhat noisy.
