### ISSUE TITLE
auto linting

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#25]
## Use Case

Linting and type consistency is beneficial for code quality!

## Acceptance Criteria

Add a gh action to automatically run lint and typecheck for this codebase.  Also clean up all current lint and typecheck errors and warnings.

## Details

Example action to copy in here: 

https://github.com/allen-cell-animated/volume-viewer/blob/main/.github/workflows/ci.yml

**Comment by ShrimpCryptid** [comment]
Also open invitation to update any linting rules we want, e.g. https://eslint.org/docs/latest/rules/prefer-const
