### ISSUE TITLE
Initial landing page implementation for colorizer

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#250]
Implement Lyndsay's design for the colorizer's landing page.

- [x] Implement page layout
- [x] Decide if the page should be the root URL (or `/landing`) -> leaning towards root URL for initial introduction, but will break all existing internal links...
- [x] Plumbing for routing existing app vs. landing page

**Comment by toloudis** [comment]
opengraph tags
small screen size warning (separate ticket)
