### ISSUE TITLE
RecordingControls should use TimeControls

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#30]
## Use Case

Internal-only, non-user affecting. Reduce code complexity by having TimeControls and RecordingControls' advancement loops use the same underlying logic, just with separate callback behavior.

## Acceptance Criteria
- When recording, the interval loop should be completely contained in TimeControls.
- Any side-effects during recording should be done as callbacks.
- Wrapping or termination behavior should be handled via callbacks.

## Details
e.g.:
```private playTimeSeries(onNewFrameCallback: () => void, onCompleted: () => void, intervalMs: number): void {}```
- Note: ok to have separate loops for timeout vs. interval if needed
- separate public entrypoint for recording

**Comment by toloudis** [comment]
also to consider:
TimeControls was intended to encapsulate all time handling.  It also encapsulates the user controls and the handlers we create. Consider a separate module called TimeController that just has the playback loop logic (with some convenient api on top of it) and TimeControls is ONLY a container for the controls and setting up their handlers, which then manipulate the TimeController.

**Comment by toloudis** [comment]
This ticket is also a good opportunity to pull out the code that gets DOM controls and binds handlers, and put it back into main, so that TimeControls and RecordingControls just contain the handlers themselves.  In which case I would change the class names to Controller instead of Controls.

**Comment by ShrimpCryptid** [comment]
Can we use just one timeout? (timeout instead of setInterval?)
