### ISSUE TITLE
Download image sequence as video/MP4

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#33]
## Use Case

@jcass11 and @vianamp requested the ability to directly download MP4 video for use on presentations and sharing.

## Acceptance Criteria

- Users can click a button to initiate a recording.
- Once the recording is finished, an encoded MP4 video will be downloaded to the user's Download directory (or the user will be prompted for a download location).
- Naming should default to the same as the existing RecordingControls.

## Details

- Similar to https://github.com/simularium/simularium-viewer/issues/252, which is running into technical issues with built-in browser security policies.

**Comment by toloudis** [comment]
Also potentially relevant: https://github.com/simularium/simularium-viewer/pull/251
