### ISSUE TITLE
Centroid data is incorrectly scaled

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#51]
## Description

Centroid coordinates are in the original dataset's coordinates, but don't match the downsampled pixel coordinates of the output frame (currently off by a factor of 4).

## Expected Behavior

Centroid coordinates should be given in the pixel coordinates of the frame.

**Comment by toloudis** [comment]
I just had a thought/guess - that this is related not to any data scaling problem, but to the scaling when we render into the viewport.  I suspect the bounding box and centroid coordinates are correct but they just need to be scaled to viewport pixels?

**Comment by ShrimpCryptid** [comment]
Good thought, I think something different might be happening. The output frame dimensions are 1140x780, but the centroids (copied from the dataset columns) are in ranges of 4560x3120. The bounds are actually correct, because they're calculated off of the frame data itself.

**Comment by ShrimpCryptid** [comment]
Update! It turns out that the images generated by `generate_data.py` are in fact 4561x3121. Dan thinks that the current images were downsampled from their original size, resulting in the mismatch between the newly generated centroid and bounding box data. 

The new list of tasks for this issue are:
- [ ] Update the `centroid.json` and `bounds.json` in the original default dataset so coordinates are decreased by a factor of four
- [ ] Remove the scaling factor introduced in https://github.com/allen-cell-animated/nucmorph-colorizer/pull/44.
- [ ] Generate a second set of test data at the original resolution to ensure the scale matches.
- [ ] Complete the downsampling feature as part of `generate_data.py`.
