### ISSUE TITLE
Scale Bar

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#56]
## Use Case

Show a scale bar on the canvas. Requested by @mogres!

## Acceptance Criteria

TBD, may need help from UX in the future (@lynwilhelm)

## Details
- May be similar to volume-viewer's solution
- Should be done in the dataset, during data generation.
- Relative to pixels or whole image?
- Overlay on top of viewport?

**Comment by toloudis** [comment]
also see #60

**Comment by ShrimpCryptid** [comment]
See implementation code from volumev-viewer by Cameron
