### ISSUE TITLE
Crash protection for data generation

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#59]
## Use Case

Currently, when `generate_data.py` crashes, it keeps the frame data but loses all intermediate work (`bounds.json`). Because the data generation scripts usually take several hours to run, issues requiring a restart (unstable run environments, terminals closing, computers going to sleep) can delay dataset processing by a whole workday.*

Ideally, the `generate_data.py` would detect if frames are missing from the dataset and start from the first missing frame.

*(\*or more; I am currently going on three days for regenerating the full-resolution datasets *😢*)*

## Acceptance Criteria

- `generate_data.py` makes backups of the bounds data to `bounds.json`.
- When making frames, the script will check if there is existing frame data in the directory and search for missing indices. If a missing frame is found, it will load the `bounds.json` and start writing bounds and frame data from that index.

## Details
- Add a flag to force overwriting the existing dataset?

**Comment by toloudis** [comment]
suggestion/alternative: command line arg with frame number or range of frames to generate.

**Comment by toloudis** [comment]
@ShrimpCryptid closing this in favor of colorizer-data ticket for bounding boxes
