### ISSUE TITLE
units

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#60]
## Use Case

As a quantitative scientific tool, we need to have units on numeric measured features.

## Acceptance Criteria

Feature data should have units.  This needs to come from the data sources.

In the viewer, we should see units on all places that display feature values.  
In particular: the editable feature range values, the hovered feature value, and the plot Y axis.  (I may have missed something here).

**Comment by ShrimpCryptid** [comment]
Here's a quick overview of all the places units should be shown.
![Image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/1d379afb-7a3d-4afa-813b-92e360e99444)

Written out:
- [ ] Min/max slider labels (but not input boxes)
- [ ] Hover tooltip
- [ ] Plot axis label
- [ ] Feature dropdown, in parentheses/italics after the unit name?
