### ISSUE TITLE
physical time

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#61]
## Use Case

As a user, I would like to see the wall clock time elapsed between frames or since the first frame.  This is useful for understanding how fast in real time the cells are actually changing.

## Acceptance Criteria

Currently the data is only represented by image number (aka frame number) in sequence. 
1. We need to obtain the wall clock times from the data source and incorporate it in the data.
2. Displaying the time elapsed from start as an overlay on the view (or elsewhere) would complete this request.

## Details

Bonus:   It could also be interesting to display this time value in the plot of a track, to help understand how long a track is.  This probably requires some nontrivial UX design.  We could promote this bonus item to a new issue.

**Comment by ShrimpCryptid** [comment]
According to Derek and Matheus, OK to assume constant time interval between frames (there is a little variation but probably okay). Most of the work of this ticket should be displaying this information in the UI.

**Comment by toloudis** [comment]
Big Question: where to display it?  overlay on viewport?  also shows up in video output?

**Comment by ShrimpCryptid** [comment]
- Just show it in the viewport as an overlay, rendered in the Canvas so it can be exported with video.
