### ISSUE TITLE
User controls for playback speed

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#65]
## Use Case

For some data, playback is actually too fast.  User Derek has requested making it adjustable.

## Acceptance Criteria

UX

**Comment by ShrimpCryptid** [comment]
- Requested the ability to slow down specifically for presentations, or trying to set a timing for how long it takes the sequence to complete.
- Graham and Jessica Yu both expressed interest in adding timing controls.
- Jess noted that it's a little fast for her too by default.
- Slider seems like it meets the use case for most folks
