### ISSUE TITLE
Provide background images for compositing

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#66]
## Use Case

From user:

If I made the track overlays into gifs for each position could they be set as background channel for the plot instead of the gray?  Would be great if background channel that is displayed was configurable so these plots could be used for validation of nuc and cell segmentation.
For nuc segmentation validation I would use the nuc channel alone.  For CAAX seg validation I would use the nuc & caax channel as a 2 color RGB image.
Making it configurable would increase the use case tremendously

## Acceptance Criteria

Prototype Idea: provide a set of background frames as pngs and composite the main view on top of them.

## Details

The user may have multiple backdrop sets they want to try out.  Probably need a blend-type parameter too.

**Comment by ShrimpCryptid** [comment]
Also related to https://github.com/allen-cell-animated/nucmorph-colorizer/issues/47

**Comment by toloudis** [comment]
Also see #95 Image Overlay

**Comment by ShrimpCryptid** [comment]
Prototyping:
- [ ] Get example images with the same length (RGB color PNGs/JPGs)
- [ ] Refactor shader with opacity settings -> overlay or blend with the background images
  - Note that current shader is opaque
  - Alternative 1: Shader could do compositing operation -> takes in background image as texture (probably most efficient/"computer graphics-y way")
  - Alternative 2: save shader image as texture and composite using Canvas (similar to #135)
  - Alternative 3: Two draw calls, do background first and then shader
