### ISSUE TITLE
Grey values out of range instead of hiding

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#69]
## Use Case

Requested by @jcass11 and @jessicasyu!
The requested feature is to indicate the existence of cells even if they're not currently being colored, giving them an alternate color instead of hiding them.

## Acceptance Criteria

- Cells outside of the range should have an alternate color applied to them instead of color ramp values.
- Add some UI element to turn on/off this feature.

**Comment by toloudis** [comment]
end goal is that values out of range can be either hidden OR use an assigned color.
