### ISSUE TITLE
Reverse Color Ramps

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#71]
## Use Case

Requested by @jessicasyu!
The convention is for the darkest colors to indicate the highest values.

![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/8fb5821c-a3e7-4274-b46d-3b60984103a8)

## Acceptance Criteria
- Adjust all existing color ramps to match convention
- Optionally, add a way to invert color ramp choices.

## Details

- Also, ideally update the URL with the color ramps and inverted state (`&colormap=Sequential_Forest/inverted`).

**Comment by toloudis** [comment]
More color ramps
https://bennettfeely.com/scales/
