### ISSUE TITLE
Set frame skip in export

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#72]
## Use Case

Requested by @jessicasyu!
When working with large datasets, sometimes it's redundant to export every frame.

## Acceptance Criteria

- Add a numeric input to the export dialog that allows the user to specify the number of frames to skip when exporting image sequences.

## Details
- Should the exported image names reflect the original frame #'s (0, 2, 4, 6) or always be in 0, 1, 2, sequence?

**Comment by jessicasyu** [comment]
I vote for keeping the original frame numbers. It helps to be able to match exported frames back to the original sequence and I think most methods for "set of images to movie" can handle non-sequential numbering.

**Comment by toloudis** [comment]
Yeah, the big question was whether tools like photoshop or whatever can read in image sequences that are disjointed like that.
