### ISSUE TITLE
Store selected color ramp in URL

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/nucmorph-colorizer#82]
## Use Case

Include color ramps when sharing via URL.

## Acceptance Criteria

- Color ramp can be stored to and fetched from the URL parameters, e.g.:
`&colormap=Sequential_Forest`
- Fall back to a default if the name is incorrect.
- Optionally, add a way to invert color ramps (`&colormap=Sequential_Forest/inverted`)

## Details
- Originally part of https://github.com/allen-cell-animated/nucmorph-colorizer/issues/71 but spun off into a new issue ticket.

**Comment by toloudis** [comment]
suggestion for inversion:  use a negative sign.  so `&colormap=Sequential_Forest` would be `&colormap=-Sequential_Forest` ! (Or could even suffix the negation instead of prefix.)
