### ISSUE TITLE
summarize new feature requests and get prioritization from scientists

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/nucmorph-colorizer#89]
## Use Case

We would like to know the 2-6 most important new features that our scientists want/need.

## Acceptance Criteria

Talk to at least 3 representative scientists from nucmorph and EMT teams and come to agreement.  Make sure there are tickets for all requests and stack rank the tickets.

## Details

Generate a summary doc that's easier to read than looking at GH lists?  Or make a GH project board that lists them and lets people assign priority?

**Comment by toloudis** [comment]
* They should not think about how much effort each item is, at first. I’d like to get an idea of what is absolutely the most valuable before we negotiate on effort and any implementation details.  Unless there’s some reason it’s just plain impossible.
* In some cases the items are still underspecified, and maybe as part of the process, we should spec out a MVP (stressing the M) with the users for any tickets where it’s not obvious.  We want to capture the usage or functionality that the user has in mind as best we can.
* the “new feature” label does not give an accurate 1-1 count of the tickets we want to present to the scientists. Maybe a new label is in order temporarily to identify those.  suggestion: `milestone 2`

**Comment by ShrimpCryptid** [comment]
https://miro.com/app/board/uXjVMofCJuU=/?share_link_id=694849182914
